# Generated by Django 3.0.8 on 2020-07-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherVerification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_signup.teacherprofile',),
        ),
    ]
