# Generated by Django 3.0.8 on 2020-08-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('subject_material', '0001_initial'),
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version_code', models.CharField(max_length=50)),
                ('app_version_name', models.CharField(max_length=50)),
                ('andriod_version', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=50)),
                ('build', models.CharField(max_length=50)),
                ('stack_trace', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstituteVerification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('classroom.institute',),
        ),
        migrations.CreateModel(
            name='TeacherVerification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_signup.teacherprofile',),
        ),
        migrations.CreateModel(
            name='VideoMaterialVerification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subject_material.videomaterial',),
        ),
    ]
