# Generated by Django 3.0.8 on 2020-08-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('administration', '0002_crashreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteVerification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('classroom.institute',),
        ),
    ]
