# Generated by Django 3.0.8 on 2020-07-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject_material', '0001_initial'),
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomaterial',
            name='teacher_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='notesmaterial',
            name='notes_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_material_link', to='subject_material.VideoMaterial'),
        ),
    ]
