# Generated by Django 3.0.8 on 2020-07-03 19:51

from django.db import migrations, models
import subject_material.models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmaterial',
            name='question_ans',
            field=models.FileField(blank=True, upload_to=subject_material.models.renaming_uploaded_file2),
        ),
    ]
