# Generated by Django 3.0.8 on 2020-07-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomaterial',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videomaterial',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
