# Generated by Django 3.0.8 on 2020-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_material', '0002_auto_20200708_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmaterial',
            name='testing',
            field=models.CharField(default='dsada', max_length=10),
        ),
    ]
