# Generated by Django 3.0.8 on 2020-07-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_material', '0002_auto_20200720_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmaterial',
            name='notes',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notesmaterial',
            name='question_ans',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
