# Generated by Django 3.0.8 on 2020-07-20 13:22

from django.db import migrations, models
import subject_material.models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_material', '0003_auto_20200720_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmaterial',
            name='notes',
            field=models.FileField(blank=True, upload_to=subject_material.models.renaming_uploaded_file1),
        ),
        migrations.AlterField(
            model_name='notesmaterial',
            name='question_ans',
            field=models.FileField(blank=True, upload_to=subject_material.models.renaming_uploaded_file2),
        ),
    ]
