# Generated by Django 3.0.8 on 2020-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_material', '0004_auto_20200720_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmaterial',
            name='misc',
            field=models.CharField(default='nothing', max_length=20),
        ),
    ]
