# Generated by Django 3.0.8 on 2020-07-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_material', '0005_notesmaterial_misc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesmaterial',
            name='misc',
        ),
    ]
