# Generated by Django 3.0.8 on 2020-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempteacher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
