# Generated by Django 3.0.8 on 2020-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course_field',
            field=models.CharField(blank=True, default='no_field', max_length=20),
        ),
    ]
