# Generated by Django 3.0.8 on 2020-07-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
