# Generated by Django 3.0.8 on 2020-08-25 19:44

import classroom.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject_material', '0001_initial'),
        ('user_signup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField()),
                ('file', models.FileField(upload_to=classroom.models.renaming_uploaded_file1)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('standard_or_class', models.CharField(default='null', max_length=10)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=20)),
                ('teacher_name', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_per_ques', models.CharField(max_length=5)),
                ('negative_marking', models.CharField(max_length=3)),
                ('starting_time', models.DateTimeField()),
                ('class_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('option', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, size=None)),
                ('answer', models.CharField(max_length=2)),
                ('ques_photo', models.ImageField(blank=True, upload_to=classroom.models.renaming_uploaded_file3)),
                ('ans_photo', models.ImageField(blank=True, upload_to=classroom.models.renaming_uploaded_file4)),
                ('explanation', models.TextField(blank=True)),
                ('public_access', models.BooleanField(default=True)),
                ('class_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_material.StandardOrClass', to_field='standard_or_class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('subject_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_material.Subject', to_field='subject_name')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('total_mark', models.CharField(max_length=5)),
                ('mark_score', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now=True)),
                ('student_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_selected', models.CharField(max_length=2)),
                ('ques_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_ques', to='classroom.QuestionBank')),
                ('student_test_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_link_test', to='classroom.StudentTest')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=25)),
                ('class_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
                ('student_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_right', models.BooleanField(default=False)),
                ('teacher_name', models.CharField(blank=True, max_length=25)),
                ('institute_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Institute')),
                ('teacher_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.TeacherProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_link_test', to='classroom.ClassTest')),
                ('ques_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.QuestionBank')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='institute_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Institute'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_signup.TeacherProfile'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_datetime', models.DateTimeField(auto_now_add=True)),
                ('time_remark', models.BooleanField(default=False)),
                ('ans_file', models.FileField(upload_to=classroom.models.renaming_uploaded_file2)),
                ('student_name', models.CharField(blank=True, max_length=25)),
                ('assignment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Assignment')),
                ('student_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_signup.StudentProfile')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Class'),
        ),
    ]
