# Generated by Django 3.0.8 on 2020-08-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=True)),
                ('admin_name', models.CharField(blank=True, max_length=20)),
                ('admin_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_signup.TeacherProfile')),
            ],
        ),
    ]
