# Generated by Django 3.0.8 on 2020-08-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtest',
            name='ending_time',
            field=models.DateTimeField(blank=True, default='2020-08-25T01:45:21+05:30'),
            preserve_default=False,
        ),
    ]
