# Generated by Django 3.0.8 on 2020-08-23 21:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionBank2',
            new_name='QuestionBank',
        ),
    ]
