# Generated by Django 3.0.8 on 2020-08-25 18:46

import classroom.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject_material', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_per_ques', models.CharField(max_length=5)),
                ('negative_marking', models.CharField(max_length=3)),
                ('starting_time', models.DateTimeField()),
                ('class_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('option', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, size=None)),
                ('answer', models.CharField(max_length=2)),
                ('ques_photo', models.ImageField(blank=True, upload_to=classroom.models.renaming_uploaded_file3)),
                ('ans_photo', models.ImageField(blank=True, upload_to=classroom.models.renaming_uploaded_file4)),
                ('explanation', models.TextField(blank=True)),
                ('public_access', models.BooleanField(default=True)),
                ('class_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_material.StandardOrClass', to_field='standard_or_class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('subject_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_material.Subject', to_field='subject_name')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('total_mark', models.CharField(max_length=5)),
                ('mark_score', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now=True)),
                ('student_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_selected', models.CharField(max_length=2)),
                ('ques_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_ques', to='classroom.QuestionBank')),
                ('student_test_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_link_test', to='classroom.StudentTest')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_link_test', to='classroom.ClassTest')),
                ('ques_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.QuestionBank')),
            ],
        ),
    ]
