# Generated by Django 3.0.8 on 2020-08-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_right', models.BooleanField(default=False)),
                ('institute_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Institute')),
                ('teacher_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.TeacherProfile')),
            ],
        ),
    ]
