# Generated by Django 3.0.8 on 2020-08-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classtest_ending_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='class_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.Class'),
        ),
    ]
