# Generated by Django 3.0.8 on 2020-08-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200824_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='subject_link',
        ),
        migrations.DeleteModel(
            name='QuestionBankSubject',
        ),
    ]
