# Generated by Django 3.0.8 on 2020-08-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='admin_link',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='admin_name',
        ),
    ]
