# Generated by Django 3.0.8 on 2020-08-24 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_material', '0001_initial'),
        ('classroom', '0003_auto_20200824_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='class_link',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='subject_material.StandardOrClass', to_field='standard_or_class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject_link',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='subject_material.Subject', to_field='subject_name'),
            preserve_default=False,
        ),
    ]
