# Generated by Django 3.0.8 on 2020-08-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_studenttest_class_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
