# Generated by Django 3.0.8 on 2020-08-24 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0004_auto_20200824_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('total_mark', models.CharField(max_length=5)),
                ('mark_score', models.CharField(max_length=5)),
                ('student_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_selected', models.CharField(max_length=2)),
                ('ques_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.QuestionBank')),
                ('student_test_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_link_test', to='classroom.StudentTest')),
            ],
        ),
    ]
