# Generated by Django 3.0.8 on 2020-08-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200811_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='class',
            name='standard_or_class',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
