# Generated by Django 3.0.8 on 2020-08-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_studenttest_studenttestdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studenttestdata',
            name='ques_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_ques', to='classroom.QuestionBank'),
        ),
    ]
