# Generated by Django 3.0.8 on 2020-09-01 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0005_auto_20200901_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='class_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Class'),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='student_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenttestdata',
            name='student_test_link',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_link_test', to='classroom.StudentTest'),
        ),
    ]
