# Generated by Django 3.0.8 on 2020-09-13 21:18

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200902_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='option',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
    ]
