# Generated by Django 3.0.8 on 2020-08-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200824_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_per_ques', models.CharField(max_length=5)),
                ('negative_marking', models.CharField(max_length=3)),
                ('starting_time', models.DateTimeField()),
                ('institute_class_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
            ],
        ),
        migrations.AlterField(
            model_name='studenttestdata',
            name='student_test_link',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_link_test', to='classroom.StudentTest'),
        ),
        migrations.CreateModel(
            name='ClassTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_link_test', to='classroom.ClassTest')),
                ('ques_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.QuestionBank')),
            ],
        ),
    ]
