# Generated by Django 3.0.8 on 2020-08-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20200825_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtest',
            old_name='institute_class_link',
            new_name='class_link',
        ),
    ]
