# Generated by Django 3.0.8 on 2020-08-14 10:35

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_datetime', models.DateField(auto_now_add=True)),
                ('end_datetime', models.DateField()),
                ('file', models.FileField(upload_to=classroom.models.renaming_uploaded_file1)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('class_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
            ],
        ),
    ]
