# Generated by Django 3.0.8 on 2020-08-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200814_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
    ]
