# Generated by Django 3.0.8 on 2020-08-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_remove_class_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='given_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
