# Generated by Django 3.0.8 on 2020-08-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20200825_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtestquestion',
            old_name='class_link',
            new_name='class_test_link',
        ),
    ]
