# Generated by Django 3.0.8 on 2020-08-15 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
        ('classroom', '0010_auto_20200815_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
                ('student_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.StudentProfile')),
            ],
        ),
    ]
