# Generated by Django 3.0.8 on 2020-08-16 06:49

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_studentattach'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_datetime', models.DateField(auto_now_add=True)),
                ('time_remark', models.BooleanField(default=False)),
                ('ans_file', models.FileField(upload_to=classroom.models.renaming_uploaded_file2)),
                ('assignment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Assignment')),
            ],
        ),
    ]
