# Generated by Django 3.0.8 on 2020-08-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0001_initial'),
        ('classroom', '0012_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student_link',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to='user_signup.StudentProfile'),
            preserve_default=False,
        ),
    ]
