# Generated by Django 3.0.8 on 2020-08-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_assignmentsubmission_student_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
