# Generated by Django 3.0.8 on 2020-08-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20200816_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteteacher',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
