# Generated by Django 3.0.8 on 2020-08-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_instituteteacher_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
