# Generated by Django 3.0.8 on 2020-08-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_class_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
