# Generated by Django 3.0.8 on 2020-07-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject_material', '0003_auto_20200705_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtsQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubts_question', models.TextField()),
                ('material_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_material.VideoMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='DoubtsQuestionPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubts_question_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.DoubtsQuestion')),
            ],
        ),
    ]
