# Generated by Django 3.0.8 on 2020-07-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_login', '0001_initial'),
        ('user_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtsquestion',
            name='teacher_link',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_signup.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='doubtsanswerphotos',
            name='doubts_answer_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_doubts_link', to='user_login.DoubtsAnswer'),
        ),
        migrations.AddField(
            model_name='doubtsanswer',
            name='answer_question_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.DoubtsQuestion'),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='comment_answer_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.DoubtsAnswer'),
        ),
    ]
