# Generated by Django 3.0.8 on 2020-07-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubtsquestionphotos',
            name='doubts_question_link',
        ),
        migrations.DeleteModel(
            name='DoubtsQuestion',
        ),
        migrations.DeleteModel(
            name='DoubtsQuestionPhotos',
        ),
    ]
